version: "3.9"

# on ne peut pas faire build ici, c'est seulement pour récupérer les images pour l'environnement de Dev

services:
  mysql:  
    image: faly3008/mysql_srvphp:latest
    container_name: laravel_mysql
    tty: true
    volumes:
      - mysql_db:/var/lib/mysql_data
    restart: always
    networks:
      - private
    environment:
      MYSQL_ROOT_PASSWORD: root

  php:
    image: faly3008/php_srvphp:latest
    container_name: php_srv
    volumes:
      - ./laravel_todo:/var/www/html
    networks:
      - private

  nginx:
    image: faly3008/srvphp:latest
    container_name: angular_nginx
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./laravel_todo:/var/www/html
    networks:
      - private
    healthcheck: # for testing if mysql has successfully initBD before running this service
      test: ["CMD", "ping", "-h", "laravel_mysql"]
      interval: 2s
      timeout: 2s
      retries: 3

volumes:
  mysql_db:
    name: compte-banque-bd

# Docker Networks
networks:
    private:
        driver: bridge