name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-angular:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build the Angular Docker image
      run: docker build ./angular --file ./angular/Dockerfile --tag my-angular-image-name:$(date +%s)

  build-laravel:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build the Laravel Docker image
      run: docker build ./laravel_todo --file ./laravel_todo/Dockerfile --tag my-laravel-image-name:$(date +%s)

  build-mysql:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build the mysql Docker image
      run: docker build ./mysql_data --file ./mysql_data/Dockerfile --tag my-mysql-image-name:$(date +%s)
